services:
  postgres:
    image: postgres:latest
    container_name: postgres-be
    environment:
      POSTGRES_DB: backend-concepts
      POSTGRES_USER: vilas
      POSTGRES_PASSWORD: vilas@123
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./backup.sql:/backup.sql
      
volumes:
  postgres_data:


# $ Run the below command to import the dump
# docker exec -t postgres psql -U recursing_fermi -d uknowme_db -f /backup.sql